---
- name: Systemd Test
  hosts: demon 
  become: true
  tasks:

#---------------------------------------------------------------------------------------------------
# Install and configure Log Scanner Service
#---------------------------------------------------------------------------------------------------
    # Передача исходных файлов юнита на удаленную машину
    - name: Add units and conffigure systemd
      template:
        src: "{{ item.src }}" 
        dest: "{{ item.dest }}"
        remote_src: no
      loop:
        - src: ./watchlog_source/watchlog.service
          dest: /etc/systemd/system/
          
        - src: ./watchlog_source/watchlog.timer
          dest: /etc/systemd/system/

        - src: ./watchlog_source/watchlog
          dest: /etc/sysconfig/watchlog
        
        - src: ./watchlog_source/watchlog.sh
          dest: /opt/

        - src: ./watchlog_source/watchlog.log
          dest: /var/log/
    # Установка разрешения на выполнения скрипта
    - name: LogScanner | Chmod script settings
      file: 
        dest=/opt/watchlog.sh mode=a+x
    # Запуск сервиса
    - name: LogScanner | Start watchlog 
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - watchlog.service
        - watchlog.timer

#---------------------------------------------------------------------------------------------------
# Install and configure Spawn-fcgi
#---------------------------------------------------------------------------------------------------
    # Передача исходных файлов юнита на удаленную машину
    - name: Spawn| Install packages
      yum:
        name: "{{ item }}"
        state: "present"
      loop:
        - epel-release
        - spawn-fcgi
        -  php 
        - php-cli 
        - mod_fcgid 
        - httpd
    # Передача исходных файлов юнита на удаленную машину
    - name: Spawn | Add units and conffigure systemd
      template:
        src: "{{ item.src }}" 
        dest: "{{ item.dest }}"
        remote_src: no
      loop:
        - src: ./spawn_source/spawn-fcgi
          dest: /etc/sysconfig/spawn-fcgi

        - src: ./spawn_source/spawn-fcgi.service
          dest: /etc/systemd/system/spawn-fcgi.service
    # Запуск сервиса
    - name: Spawn | restart spawn
      systemd:
        name: spawn-fcgi
        state: started
        enabled: yes
#---------------------------------------------------------------------------------------------------
# Install and configure httpd-service
#---------------------------------------------------------------------------------------------------
# Передача исходных файлов юнита на удаленную машину
    - name: Httpd | Install packages
      yum:
        name: httpd
        state: "present"

    # Передача исходных файлов юнита на удаленную машину
    - name: Httpd | Add units and conffigure systemd
      template:
        src: "{{ item.src }}" 
        dest: "{{ item.dest }}"
        remote_src: no
      loop:
        - src: ./httpd_source/httpd@.service
          dest: /etc/systemd/system/httpd@.service

        - src: ./httpd_source/httpd-first
          dest: /etc/sysconfig/httpd-first

        - src: ./httpd_source/httpd-second
          dest: /etc/sysconfig/httpd-second

        - src: ./httpd_source/first.conf
          dest: /etc/httpd/conf/first.conf

        - src: ./httpd_source/second.conf
          dest: /etc/httpd/conf/second.conf 
    #  Запуск сервиса
    - name: Httpd | estart service
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - httpd@first
        - httpd@second