---
- name: LogScanner | Install and configure Log Scanner Service
  hosts: demon 
  become: true
  tasks:
    # Передача исходных файлов юнита на удаленную машину
    - name: Add units and conffigure systemd
      template:
        src: "{{ item.src }}" 
        dest: "{{ item.dest }}"
        remote_src: no
      loop:
        - src: ./watchlog_source/watchlog.service
          dest: /etc/systemd/system/
          
        - src: ./watchlog_source/watchlog.timer
          dest: /etc/systemd/system/

        - src: ./watchlog_source/watchlog
          dest: /etc/sysconfig/watchlog
        
        - src: ./watchlog_source/watchlog.sh
          dest: /opt/

        - src: ./watchlog_source/watchlog.log
          dest: /var/log/
      notify:
        - chmod script
        - restart watchlog

  handlers:
  - name: restart watchlog
    systemd:
      name: "{{ item }}"
      state: restarted
      enabled: yes
    loop:
      - wathclog.service
      - watchlog.timer
  
  - name: chmod script
    file: 
      dest=/opt/watchlog.sh mode=a+x